"""add_stage4_pregnancy_foundation

Revision ID: 7948cc6afd42
Revises: 8158a58d5b82
Create Date: 2026-10-04 12:28:57.954831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7948cc6afd42'
down_revision: Union[str, Sequence[str], None] = '8158a58d5b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pregnancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'TERMINATED', 'UNKNOWN', name='pregnancy_status_enum'), nullable=False),
    sa.Column('lmp', sa.Date(), nullable=False),
    sa.Column('edd', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pregnancy_number > 0', name='ck_pregnancy_number_positive'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'pregnancy_number', name='uq_patient_pregnancy_number')
    )
    op.create_index(op.f('ix_pregnancies_id'), 'pregnancies', ['id'], unique=False)
    op.create_index(op.f('ix_pregnancies_patient_id'), 'pregnancies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pregnancies_status'), 'pregnancies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pregnancies_status'), table_name='pregnancies')
    op.drop_index(op.f('ix_pregnancies_patient_id'), table_name='pregnancies')
    op.drop_index(op.f('ix_pregnancies_id'), table_name='pregnancies')
    op.drop_table('pregnancies')
    # ### end Alembic commands ###
