"""add_stage5_asha_vitals_visits

Revision ID: c6c7cacdc894
Revises: 7948cc6afd42
Create Date: 2026-10-04 13:10:24.280824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c7cacdc894'
down_revision: Union[str, Sequence[str], None] = '7948cc6afd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asha_patient_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asha_worker_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='assignment_status_enum'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asha_worker_id'], ['asha_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asha_patient_assignments_asha_worker_id'), 'asha_patient_assignments', ['asha_worker_id'], unique=False)
    op.create_index(op.f('ix_asha_patient_assignments_id'), 'asha_patient_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_asha_patient_assignments_patient_id'), 'asha_patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_asha_patient_assignments_status'), 'asha_patient_assignments', ['status'], unique=False)
    op.create_table('home_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_id', sa.UUID(), nullable=True),
    sa.Column('asha_worker_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'CANCELLED', name='visit_status_enum'), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asha_worker_id'], ['asha_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_visits_asha_worker_id'), 'home_visits', ['asha_worker_id'], unique=False)
    op.create_index(op.f('ix_home_visits_id'), 'home_visits', ['id'], unique=False)
    op.create_index(op.f('ix_home_visits_patient_id'), 'home_visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_home_visits_pregnancy_id'), 'home_visits', ['pregnancy_id'], unique=False)
    op.create_index(op.f('ix_home_visits_status'), 'home_visits', ['status'], unique=False)
    op.create_index(op.f('ix_home_visits_visit_date'), 'home_visits', ['visit_date'], unique=False)
    op.create_table('maternal_vital_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_id', sa.UUID(), nullable=False),
    sa.Column('home_visit_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('diastolic_bp IS NULL OR (diastolic_bp >= 20 AND diastolic_bp <= 200)', name='ck_vitals_diastolic_bp'),
    sa.CheckConstraint('systolic_bp IS NULL OR (systolic_bp >= 40 AND systolic_bp <= 300)', name='ck_vitals_systolic_bp'),
    sa.CheckConstraint('temperature_c IS NULL OR (temperature_c >= 30.0 AND temperature_c <= 45.0)', name='ck_vitals_temperature_c'),
    sa.CheckConstraint('weight_kg IS NULL OR (weight_kg >= 20.0 AND weight_kg <= 300.0)', name='ck_vitals_weight_kg'),
    sa.ForeignKeyConstraint(['home_visit_id'], ['home_visits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maternal_vital_records_home_visit_id'), 'maternal_vital_records', ['home_visit_id'], unique=False)
    op.create_index(op.f('ix_maternal_vital_records_id'), 'maternal_vital_records', ['id'], unique=False)
    op.create_index(op.f('ix_maternal_vital_records_pregnancy_id'), 'maternal_vital_records', ['pregnancy_id'], unique=False)
    op.create_index(op.f('ix_maternal_vital_records_recorded_at'), 'maternal_vital_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_maternal_vital_records_recorded_by_user_id'), 'maternal_vital_records', ['recorded_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maternal_vital_records_recorded_by_user_id'), table_name='maternal_vital_records')
    op.drop_index(op.f('ix_maternal_vital_records_recorded_at'), table_name='maternal_vital_records')
    op.drop_index(op.f('ix_maternal_vital_records_pregnancy_id'), table_name='maternal_vital_records')
    op.drop_index(op.f('ix_maternal_vital_records_id'), table_name='maternal_vital_records')
    op.drop_index(op.f('ix_maternal_vital_records_home_visit_id'), table_name='maternal_vital_records')
    op.drop_table('maternal_vital_records')
    op.drop_index(op.f('ix_home_visits_visit_date'), table_name='home_visits')
    op.drop_index(op.f('ix_home_visits_status'), table_name='home_visits')
    op.drop_index(op.f('ix_home_visits_pregnancy_id'), table_name='home_visits')
    op.drop_index(op.f('ix_home_visits_patient_id'), table_name='home_visits')
    op.drop_index(op.f('ix_home_visits_id'), table_name='home_visits')
    op.drop_index(op.f('ix_home_visits_asha_worker_id'), table_name='home_visits')
    op.drop_table('home_visits')
    op.drop_index(op.f('ix_asha_patient_assignments_status'), table_name='asha_patient_assignments')
    op.drop_index(op.f('ix_asha_patient_assignments_patient_id'), table_name='asha_patient_assignments')
    op.drop_index(op.f('ix_asha_patient_assignments_id'), table_name='asha_patient_assignments')
    op.drop_index(op.f('ix_asha_patient_assignments_asha_worker_id'), table_name='asha_patient_assignments')
    op.drop_table('asha_patient_assignments')
    # ### end Alembic commands ###
